// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/chat.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f4599e5c255691, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type CreateUserResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f4599e5c255691, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "example.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "example.CreateUserResponse")
}

func init() { proto.RegisterFile("api/chat.proto", fileDescriptor_73f4599e5c255691) }

var fileDescriptor_73f4599e5c255691 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4a, 0xc3, 0x50,
	0x10, 0x86, 0x69, 0xb4, 0x4a, 0x47, 0x09, 0x38, 0x74, 0x11, 0xa2, 0xa2, 0x64, 0xe5, 0x2a, 0x01,
	0x3d, 0x42, 0x96, 0xee, 0x22, 0x75, 0xe3, 0x22, 0x8c, 0xc9, 0xd0, 0x06, 0xd2, 0x4c, 0x9c, 0x37,
	0x29, 0xae, 0xbd, 0x82, 0x47, 0xf3, 0x0a, 0x1e, 0x44, 0x7c, 0xaf, 0xa0, 0xa0, 0xbb, 0xf7, 0xfe,
	0x6f, 0xf8, 0xff, 0xf9, 0x07, 0x62, 0x1a, 0xbb, 0xa2, 0xd9, 0x90, 0xe5, 0xa3, 0x8a, 0x09, 0x1e,
	0xf3, 0x2b, 0x6d, 0xc7, 0x9e, 0xd3, 0x8b, 0xb5, 0xc8, 0xba, 0xe7, 0xe2, 0x9b, 0xd3, 0x30, 0x88,
	0x91, 0x75, 0x32, 0xb8, 0x30, 0x96, 0x3d, 0xc2, 0x59, 0xa9, 0x4c, 0xc6, 0x2b, 0xc7, 0x5a, 0xf1,
	0xcb, 0xc4, 0xce, 0x30, 0x86, 0xa8, 0x6b, 0x93, 0xd9, 0xf5, 0xec, 0x66, 0x51, 0x45, 0x5d, 0x8b,
	0x08, 0x87, 0x03, 0x6d, 0x39, 0x89, 0xbc, 0xe2, 0xdf, 0x78, 0x09, 0x40, 0x3b, 0x32, 0xd2, 0x7a,
	0xd2, 0x3e, 0x39, 0xf0, 0x64, 0x11, 0x94, 0x95, 0xf6, 0xd9, 0x3d, 0xe0, 0x6f, 0x5f, 0x37, 0xca,
	0xe0, 0x18, 0xaf, 0xe0, 0xc4, 0x19, 0xd9, 0xe4, 0xea, 0x46, 0x5a, 0xf6, 0x09, 0xf3, 0x0a, 0x82,
	0x54, 0x4a, 0xcb, 0xb8, 0x84, 0x39, 0xab, 0x8a, 0xee, 0xa3, 0xc2, 0xe7, 0xb6, 0x03, 0x28, 0x37,
	0x64, 0x0f, 0xac, 0x3b, 0x56, 0x7c, 0x02, 0xf8, 0xb1, 0xc6, 0x34, 0xdf, 0x17, 0xcd, 0xff, 0xf4,
	0x48, 0xcf, 0xff, 0x65, 0x61, 0x97, 0x6c, 0xf9, 0xf6, 0xf1, 0xf9, 0x1e, 0xc5, 0xd9, 0x69, 0xd1,
	0x78, 0x58, 0x4f, 0x8e, 0xf5, 0xf9, 0xc8, 0x9f, 0xe5, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x34,
	0xde, 0xa4, 0x2e, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServerClient is the client API for ChatServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServerClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type chatServerClient struct {
	cc *grpc.ClientConn
}

func NewChatServerClient(cc *grpc.ClientConn) ChatServerClient {
	return &chatServerClient{cc}
}

func (c *chatServerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/example.ChatServer/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServerServer is the server API for ChatServer service.
type ChatServerServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedChatServerServer can be embedded to have forward compatible implementations.
type UnimplementedChatServerServer struct {
}

func (*UnimplementedChatServerServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterChatServerServer(s *grpc.Server, srv ChatServerServer) {
	s.RegisterService(&_ChatServer_serviceDesc, srv)
}

func _ChatServer_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ChatServer/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServerServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.ChatServer",
	HandlerType: (*ChatServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _ChatServer_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/chat.proto",
}
