// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f4599e5c255691, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type CreateUserResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f4599e5c255691, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
}

func init() { proto.RegisterFile("api/chat.proto", fileDescriptor_73f4599e5c255691) }

var fileDescriptor_73f4599e5c255691 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4a, 0xc3, 0x50,
	0x10, 0x86, 0x69, 0xb4, 0x42, 0x47, 0x09, 0x38, 0x76, 0x11, 0x8a, 0xa2, 0x64, 0xe5, 0x2a, 0x01,
	0x3d, 0x42, 0x96, 0xdd, 0x45, 0x2a, 0xb8, 0x0a, 0x63, 0x32, 0xb4, 0x81, 0xf8, 0x26, 0xce, 0x9b,
	0xf4, 0x00, 0x5e, 0xc1, 0xa3, 0x79, 0x05, 0x0f, 0x22, 0xbe, 0x27, 0x58, 0xe8, 0x6e, 0xe6, 0xfb,
	0xe1, 0xff, 0x86, 0x81, 0x94, 0xc6, 0xbe, 0x6c, 0x77, 0x64, 0xc5, 0xa8, 0x62, 0xb2, 0xba, 0xde,
	0x8a, 0x6c, 0x07, 0x2e, 0x7f, 0x31, 0x39, 0x27, 0x46, 0xd6, 0x8b, 0xf3, 0x31, 0xcd, 0x9f, 0xe1,
	0xb2, 0x52, 0x26, 0xe3, 0x8d, 0x67, 0xad, 0xf9, 0x7d, 0x62, 0x6f, 0x98, 0x42, 0xd2, 0x77, 0xd9,
	0xec, 0x6e, 0x76, 0xbf, 0xa8, 0x93, 0xbe, 0x43, 0x84, 0x53, 0x47, 0x6f, 0x9c, 0x25, 0x81, 0x84,
	0x19, 0x6f, 0x00, 0x68, 0x4f, 0x46, 0xda, 0x4c, 0x3a, 0x64, 0x27, 0x21, 0x59, 0x44, 0xb2, 0xd1,
	0x21, 0x5f, 0x03, 0x1e, 0xf6, 0xfa, 0x51, 0x9c, 0x67, 0xbc, 0x85, 0x73, 0x6f, 0x64, 0x93, 0x6f,
	0x5a, 0xe9, 0x38, 0x18, 0xe6, 0x35, 0x44, 0x54, 0x49, 0xc7, 0xb8, 0x84, 0x39, 0xab, 0x8a, 0xfe,
	0xa9, 0xe2, 0xf2, 0xf0, 0x02, 0x50, 0xed, 0xc8, 0x9e, 0x58, 0xf7, 0xac, 0xb8, 0x06, 0xf8, 0xaf,
	0x46, 0x2c, 0x8e, 0xee, 0x5f, 0x5d, 0x15, 0xc7, 0xee, 0x7c, 0xf9, 0xf1, 0xf5, 0xfd, 0x99, 0xa4,
	0x78, 0x51, 0xb6, 0x21, 0x6c, 0x26, 0xcf, 0xfa, 0x7a, 0x16, 0xde, 0xf0, 0xf8, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x91, 0xb5, 0x3b, 0x73, 0x36, 0x01, 0x00, 0x00,
}
